# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GarethG | Junior Fullstack Web Developer
email: me@garethg.com
description: GarethG | Junior Web Developer | Lover of French Bulldogs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ggomersall.github.io" # the base hostname & protocol for your site
twitter_username: GarethG_
github_username:  ggomersall
exclude: ['README.md', 'GEMFILE', 'GEMFILE.lock']

# Build settings
markdown: kramdown
